#!/bin/sh
git clone git://dev.entermediasoftware.com/entermedia-core.git entermedia-core
git clone git://dev.entermediasoftware.com/entermedia-server.git entermedia-server
git clone git://dev.entermediasoftware.com/demoall.git demoall
git clone git://dev.entermediasoftware.com/app-emshare.git app-emshare
git clone git://dev.entermediasoftware.com/resin3.x.git resin3.x
git clone git://dev.entermediasoftware.com/client-rest-java.git client-rest-java
git clone git://dev.entermediasoftware.com/extension-aspera.git extension-aspera
git clone git://dev.entermediasoftware.com/extension-cumulus.git extension-cumulus
git clone git://dev.entermediasoftware.com/extension-elasticsearch.git extension-elasticsearch
git clone git://dev.entermediasoftware.com/extension-episode.git extension-episode
git clone git://dev.entermediasoftware.com/extension-fatwire.git extension-fatwire
git clone git://dev.entermediasoftware.com/extension-ooffice.git extension-ooffice
git clone git://dev.entermediasoftware.com/extension-openedit.git extension-openedit
git clone git://dev.entermediasoftware.com/extension-rhozet.git extension-rhozet
git clone git://dev.entermediasoftware.com/extension-smartjog.git extension-smartjog
git clone git://dev.entermediasoftware.com/extension-sql.git extension-sql
git clone git://dev.entermediasoftware.com/extension-uploader.git extension-uploader
git clone git://dev.entermediasoftware.com/extension-webdav.git extension-webdav
git clone git://dev.entermediasoftware.com/extension-oraclesso.git extension-oraclesso
git clone git://dev.entermediasoftware.com/app-emtube.git app-emtube
git clone git://dev.entermediasoftware.com/app-loudmouth.git app-loudmouth
git clone git://dev.entermediasoftware.com/app-medialab.git app-medialab
git clone git://dev.entermediasoftware.com/app-mediamoneymaker.git app-mediamoneymaker
git clone git://dev.entermediasoftware.com/app-scout.git app-scout
git clone git://dev.entermediasoftware.com/app-sundial.git app-sundial
git clone git://dev.entermediasoftware.com/app-workmonger.git app-workmonger